m6-t1
htmlacademy-ecmascript/43376-cinemaddict-16 pull request #11
Opened 2021-12-18 23:38 UTC by DragaTM

2021-12-29 09:57 UTC, slyvkanychmykyta requested changes

2021-12-29 09:57 UTC, slyvkanychmykyta commented on src/presenter/film-presenter.js
> +let openedPopup = null;
эту переменную нужно добавить в filmPresenter, так как она относится именно к нему. Можно назвать ее по типу `#currentFilmDetails`

2021-12-29 09:57 UTC, slyvkanychmykyta commented on src/presenter/main-presenter.js
> +        this.#films.sort((filmA, filmB) => {const result = filmB.rating - filmA.rating; return result;});
коллбеки сортировки лучше вынести в  utils. Будет что-то вроде 
`const sortFilmByRating = (filmA, filmB) => filmB.rating - filmA.rating`
А при вызове `this.#films.sort(sortFilmByRating);`

2021-12-29 09:57 UTC, slyvkanychmykyta commented on src/view/details-view.js
> +      activeEmoji: 'smile',
названия  emoji нужно вынести в групповую константу (объект). Также, названия обработчиков должны быть такого типа - #названиеДействиеHandler, например - `#emojiSmileСlickHandler`. Вообще, можно использовать делегирование, навесить обработчик клика по emoji на контейнер, а потом уже по evt.target вычислять айди скликнутого emoji, тогда будет не 4 обработчика, а 1

2021-12-30 07:18 UTC, DragaTM commented on src/view/details-view.js
> +      activeEmoji: 'smile',
переделал

2021-12-30 07:18 UTC, DragaTM commented on src/presenter/main-presenter.js
> +        this.#films.sort((filmA, filmB) => {const result = filmB.rating - filmA.rating; return result;});
поправил

2021-12-30 07:21 UTC, DragaTM commented on src/presenter/film-presenter.js
> +let openedPopup = null;
тут нельзя так сделать, потому что Popup не относится к презентеру, презентеров много, а Popup один, и открытый Popup может не соответствовать текущему презентеру

2021-12-30 19:17 UTC, slyvkanychmykyta approved these changes

2021-12-30 19:17 UTC, merged