Module7 task1
htmlacademy-ecmascript/43376-cinemaddict-16 pull request #12
Opened 2021-12-31 00:43 UTC by DragaTM

2022-01-11 18:28 UTC, slyvkanychmykyta requested changes

2022-01-11 18:28 UTC, slyvkanychmykyta commented on src/presenter/main-presenter.js
> +    switch (this.#currentSortType) {
здесь можно убрать switch, просто добавить две проверки

2022-01-11 18:28 UTC, slyvkanychmykyta commented on src/presenter/main-presenter.js
> +  #clearMain = ({resetSortType = false} = {}) => {
мне кажется {resetSortType = false} будет достаточно

2022-01-11 18:28 UTC, slyvkanychmykyta commented on src/utils.js
> +export const isSubmitKeys = (e) => {
`const isSubmitKeys = (e) => e.keyCode === 13 && e.ctrlKey`; 13  нужно вынести в константу

2022-01-11 18:28 UTC, slyvkanychmykyta commented on src/view/sort-view.js
> +    if (evt.target.tagName !== 'A') {
нужно вынести в константы 'A' и 'INPUT'

2022-01-12 16:53 UTC, slyvkanychmykyta requested changes

2022-01-12 16:53 UTC, slyvkanychmykyta commented on src/const.js
> +  if (e.keyCode === 13 && e.ctrlKey) {
почему не упростил?

2022-01-12 16:53 UTC, slyvkanychmykyta commented on src/const.js
> +export const isClickOnTab = (e) => {
почему клик по табу? Клик по ссылке же

2022-01-12 16:53 UTC, slyvkanychmykyta commented on src/const.js
> +export const isOnEmojiClick = (e) => {
название функции неправильно описывает ее действие. Эта функция проверят, был ли осущетсвлен клик по инпуту, никак не по emoji.

2022-01-12 16:56 UTC, DragaTM commented on src/view/filter-view.js
> +    if (evt.target.tagName !== 'A') {
это я уже вторую часть задания начал делать

2022-01-12 17:17 UTC, DragaTM commented on src/view/stats-view.js
> +      plugins: [ChartDataLabels],
это я уже вторую часть задания начал делать

2022-01-12 17:45 UTC, merged